### ISSUE TITLE
Fuite crashing unexpectedly as if any exceptions from toString() are not handled

### ISSUE THREAD

**Issue by rmr949** [nolanlawson/fuite#73] opened 2023-01-09 11:09 UTC
Hi, 
Firstly, thanks for this amazing tool. This has been helpful to accelerate our memory leak testing!

We are facing an issue and below are the details. It would really help us if you can handle this. Or if you can give us permissions, we can raise the pull request as well.

Issue:
Fuite crashes unexpectedly while collecting the heap metrics. 

Root cause:
- In one of our object classes, toString() throws 'NotImplemented' error. This is a legacy code and we dont want to modify this for now.
- But because of this exception below method in collections.js throws unhandled exception and the Fuite crashes. This is completely blocking our testing.

`        function isObject (o) {
          return toString.call(o) === '[object Object]'
        }`

Possible fix:
Handle this in a try catch just like its already handled in getSize() method in same file

```
        function isObject (o) {
          try {
            return toString.call(o) === '[object Object]'
          } catch (error) {
          // If for whatever reason the tostring() errors (e.g. tostring throws notImplemented exception), return false.
          // Handling this gracefully to avoid Fuite crashes itself
           return false 
          }
        }
```

**Comment by rmr949** [comment] 2023-01-09 11:11
@nolanlawson - Can you please take a look into this? This is currently blocking our testing and this will help unblock us and avoid making the changes in a fork.

**Comment by nolanlawson** [comment] 2023-01-14 18:13
Digging into this a bit further – I'm not sure how it's possible for your code to be throwing.

If I have a basic class that throws in `toString()`:

```js
class Foo {
  toString() {
    throw new Error('not implemented')
  }
}
```

And then I call `Object.prototype.toString` on it, exactly as `fuite` is doing:

```js
Object.prototype.toString.call(new Foo())
```

Then it prints out:

```js
'[object Object]'
```

So it doesn't actually throw an error.

Could you explain how it's possible for fuite to throw an error here? A minimal repro would be great. Thanks!

**Comment by nolanlawson** [comment] 2024-05-19 18:49
Closing as I cannot reproduce, please reopen if you have a repro. Thank you!

**Closed by nolanlawson** 2024-05-19 18:49 UTC
